from __future__ import annotations
import json, shutil, subprocess
from pathlib import Path

def _scad(spec,part):
    ix=float(spec["inner_x_mm"]); iy=float(spec["inner_y_mm"]); iz=float(spec["inner_z_mm"])
    wall=float(spec["wall_mm"]); lid=float(spec.get("lid_thickness_mm",wall))
    clearance=float(spec.get("clearance_mm",0.3))
    ox=ix+2*wall; oy=iy+2*wall; oz=iz+wall
    if part=="body":
        return f"""// Generated by IdeaForge
$fn=48;
difference() {{
  cube([{ox},{oy},{oz}]);
  translate([{wall},{wall},{wall}])
    cube([{ix},{iy},{iz+wall+1}]);
}}
"""
    return f"""// Generated by IdeaForge
$fn=48;
difference() {{
  cube([{ox+2*clearance},{oy+2*clearance},{lid}]);
  translate([{wall-clearance},{wall-clearance},{lid/2}])
    cube([{ix+2*clearance},{iy+2*clearance},{lid+1}]);
}}
"""

def generate(spec_path,out_dir=None):
    spec=json.loads(Path(spec_path).read_text(encoding="utf-8"))
    out=Path(out_dir or Path(spec_path).parent/"generated")
    out.mkdir(parents=True,exist_ok=True)
    body=out/"body.scad"; lid=out/"lid.scad"
    body.write_text(_scad(spec,"body"),encoding="utf-8")
    lid.write_text(_scad(spec,"lid"),encoding="utf-8")
    openscad=shutil.which("openscad")
    rendered=[]
    if openscad:
        for scad in (body,lid):
            stl=scad.with_suffix(".stl")
            subprocess.run([openscad,"-o",str(stl),str(scad)],check=True)
            rendered.append(str(stl))
    receipt={"spec":spec,"scad":[str(body),str(lid)],"stl":rendered,"openscad_found":bool(openscad)}
    (out/"generation.json").write_text(json.dumps(receipt,indent=2),encoding="utf-8")
    return receipt

if __name__=="__main__":
    import argparse
    p=argparse.ArgumentParser(); p.add_argument("spec"); p.add_argument("--out"); a=p.parse_args()
    print(json.dumps(generate(a.spec,a.out),indent=2))
