"""Versioned registry metadata vocabulary; recognition confers no scientific or runtime acceptance."""

REGISTRY_EVIDENCE_VOCABULARY_VERSION = "descriptive-evidence-20261007.v1"

# Exact already-published descriptive strings. This is a frozen, explicit source
# allowlist, never populated from a registry at runtime. Do not normalize/trim
# or map these descriptions to measured/inferred biological evidence.
DESCRIPTIVE_EVIDENCE_V1 = frozenset({
    'AST import roster with exact immutable source hashes and prior published-version links.',
    'Attributed projection from final exact independently reviewed metadata source/actual/own bytes; no scientific result or runtime authority inferred.',
    'Different source, scientific, physical IO and final saved-document review; original returns privately retained. Public role: capability_scope.',
    'Different source, scientific, physical IO and final saved-document review; original returns privately retained. Public role: complete_reference_source.',
    'Different source, scientific, physical IO and final saved-document review; original returns privately retained. Public role: cost_scope.',
    'Different source, scientific, physical IO and final saved-document review; original returns privately retained. Public role: failure_history.',
    'Different source, scientific, physical IO and final saved-document review; original returns privately retained. Public role: method.',
    'Different source, scientific, physical IO and final saved-document review; original returns privately retained. Public role: qualified_costs.',
    'Different source, scientific, physical IO and final saved-document review; original returns privately retained. Public role: qualified_results.',
    'Different source, scientific, physical IO and final saved-document review; original returns privately retained. Public role: readable_results.',
    'Different source, scientific, physical IO and final saved-document review; original returns privately retained. Public role: scientific_review.',
    'Different source, scientific, physical IO and final saved-document review; original returns privately retained. Public role: source_scope.',
    'Different source, scientific, physical IO and final saved-document review; original returns privately retained. Public role: unrun_research.',
    'Eight original paired model jobs with no learning, separate original passive scorer and independently reconstructed science/IO; incomplete earlier metadata attempts retained.',
    'Exact generic bytes with separate recorded independent qualification; no private source packet is published.',
    'Exact generic component bytes or attributed document projection; separate independent source, process/IO and scientific qualifications control each claim.',
    'Exact independent actual review generic projection or attributed bounded synthesis from it; raw private evidence excluded.',
    'Exact independent reviewed generic results or attributed document-only projection; zero of six fresh component gates passed; all54protected checks retained.',
    'Exact independently reviewed current source bytes; metadata-only packaging.',
    'Exact independently reviewed generic method/source projection; original stage status retained.',
    'Exact independently reviewed generic source or attributed bounded projection; actual221 science remains pending.',
    'Exact independently reviewed generic source or explicitly attributed count-only projection; actual221 outcomes remain pending.',
    'Exact original scorer source retained as failed-scoring history; original25 remains target1 and old26-28 remain unrun.',
    'Exact retained source metadata, independent numerical review and attributed published external reports. All new routing and connected engineering numerical work is UNRUN.',
    'Exact reviewed generic project source or complete independently reviewed metric-only observations',
    'Exact saved generic source or AST/disk-byte dependency/version projection; source packaging only.',
    'Exact saved source or independently reviewed generic projection; complete private provenance bound separately.',
    'Exact seven original source bytes plus complete role/version closure and independent review; separate historical074/075 recorded local results unchanged.',
    'Exact source or explicitly attributed generic projection of independently reviewed count-only correction; actual method outcomes remain pending.',
    'Exact source/engineering/scientific/physical IO and final document reviews; original returns retained privately. No neural/scorer replay by curator.',
    'Independent exact casewise and IO recomputation of one original passive run; generic source binding placeholders explicitly attributed and unexecuted.',
    'Independently reviewed generic projection of original failed synthetic engineering and saved-byte diagnosis; no normal acceptance or semantic score.',
    'Independently reviewed generic projection of qualified original eight-update synthetic engineering; exact source references and separately scoped costs. No semantic score or real-main migration.',
    'One original inherited zero-SGD migration saved operands/metadata independently reviewed; public parent is an earlier method reference, not private model ancestry',
    'Pinned upstream source and passive local source assessment; no newly executed numerical or voice result.',
    'Saved exact reviewed project source or independently recomputed generic observations',
    'The independently reviewed second scoring failure and narrow source correction; fresh score results remain pending.',
    'derived-reviewed-method-summary',
    'derived-reviewed-result-summary',
    'exact-preserved-published-history',
    'independent-actual-review-projection',
    'independent-adverse-source-review',
    'independent-source-data-review',
    'independent-source-review',
    'independently-reviewed-saved-metric-projection',
    'observed-controlled-component-result',
    'observed-engineering-fixture-result',
    'observed-engineering-result',
    'observed-process-source-and-IO-result',
    'observed-reporting-failure',
    'project-authored-reviewed-metric-projection',
    'project-authored-reviewed-metric-scope-comparison',
    'project-authored-source',
    'project-authored-source-or-independent-saved-metadata-review',
    'reviewed-source-and-observed-results',
    'saved-actual-diagnostic-metadata',
})
